### ISSUE TITLE
Add Meta descriptions to all pages on the website

### ISSUE THREAD

**Issue by bellelala** [AElf-devops/aelf-website-next#53]
<img width="1582" alt="developer aelf website - meta title only" src="https://github.com/AElf-devops/aelf-website-next/assets/174006071/301907dc-be93-4b1b-a469-49e4e4d7eee5">
<img width="1037" alt="docs aelf website - update meta description" src="https://github.com/AElf-devops/aelf-website-next/assets/174006071/2b4aca6c-5c7b-427d-84b3-00c5877134a1">
<img width="1591" alt="ecosystem aelf website - meta title only" src="https://github.com/AElf-devops/aelf-website-next/assets/174006071/8723fe4f-8616-4984-a67c-0627de6be010">
<img width="1131" alt="google - aelf - nft meta description" src="https://github.com/AElf-devops/aelf-website-next/assets/174006071/6fa5f7b9-f5e0-478b-836c-69c6629ec0eb">
<img width="969" alt="google - ai blockchain aelf - meta description" src="https://github.com/AElf-devops/aelf-website-next/assets/174006071/0d5eb9fd-748b-49eb-8822-364f32b8e9bc">
<img width="1518" alt="home aelf website - meta title only" src="https://github.com/AElf-devops/aelf-website-next/assets/174006071/2eb11d39-1dec-43a8-b80d-bda079491317">

### Need to add new Meta description for all pages on the new aelf.com website.

Meta description for 
**1. home page - https://aelf.com/**
aelf: High-performance AI blockchain for Web3 DApps with AI-powered tools & scalable infrastructure for developers to build, deploy & manage dApps efficiently.

**2. docs page - https://docs.aelf.com/**
Explore aelf's documentation for in-depth guides on its high-performance AI blockchain, scalable infrastructure & tools for building & managing Web3 DApps.

**3. developer page - https://aelf.com/developer-center**
Learn how to build on aelf with our detailed documentation. Discover AI blockchain tools and scalable infrastructure for high-performance Web3 DApps.

**4. ecosystem page - https://aelf.com/ecosystem**
Explore the aelf ecosystem with cutting-edge AI blockchain technology. Discover the diverse dApps for various use cases in the Web3 crypto industry.

**5. platform page - https://www.aelf.com/platform**
Deep dive into aelf's high-performance AI blockchain platform with cross-chain interoperability and a robust ecosystem for seamless Web3 DApp development.

 
Also, when you google search "aelf" and "ai blockchain aelf", the meta description is not consistent. Please refer to the 2 screenshots "google - aelf - nft meta description" and "google - ai blockchain aelf - meta description". 
Please check it and ensure they are all updated with the new "home page" meta description provided above.

**Comment by CallaChen111** [comment]
The docs page needs other project to be added, and others can be added

**Comment by bellelala** [comment]
> The docs page needs other project to be added, and others can be added

![image](https://github.com/AElf-devops/aelf-website-next/assets/174006071/6fd8e54b-a774-4605-b057-634ed390f8e7)
Meta description updated for https://docs.aelf.com/
